<!DOCTYPE html>
<html>
<head>
    <title>小萝卜</title>
    <meta charset="UTF-8">
    <title></title>
    <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/scripts/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/scripts/jquery/css/jquery.alerts.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/styles/admin/style.css" />
    <style type="text/css">
        li{
            display: inline-block;
            cursor: pointer;
        }
        a{
            color: #838a90;
        }
        a:hover {
            color: #4aacf3;
            text-decoration: none;
        }
        #add_user button{
            margin-right: 20px;
        }

        .display-none{
            display: none;
        }
        .form-control{
            width: 90%;
            float: left;
        }
        .xln_must_enter {
            color: #c00000;
            font-size: 16px;
            float: left;
            padding-left: 10px;
            height: 40px;
            line-height: 40px;
        }
        form .errMsg{
            color: #A94442;
        }
        .form-horizontal .form-group {
            margin: 0px 0px 20px 0px;
        }
        .control-input {
            min-height: 40px;
            float: left;
            color: #4d4d4d;
        }
        .form-horizontal .control-label {
            font-size: 12px;
            color: #121212;
            font-weight: normal;
            float: left;
            height: 40px;
            line-height: 40px;
            padding: 0px;
        }
        .input-group-addon.search {
            cursor: pointer;
            width: 34px;
            height: 34px;
            border: none;
            background: transparent url(/xlb/public/images/search.png) no-repeat scroll 10px 10px;
        }
        .span_user{
            height: 40px;
            width: 50px;
            background: #2294e4;
            float: left;
            border: 1px solid #2294e4;
            border-radius: 0px 4px 4px 0px;
            padding: 0px;
            cursor: pointer;
        }
        #xz_sp button{
        }
    </style>
</head>
<body style="height: 100%">
<div class="container" style="border-radius: 4px;height: 100%;width: 100%;background-color: #fff;overflow-y: auto">
    <div id="user_list">
        <div style="margin: 20px 20px 50px;">
            <div style="width:100%;color:#74767c;font-size:18px;">用户列表</div>
            <div style="padding-right: 20px;">
                <div class="float-right">
                    <form action="/xlb/admin/user/index/page/1" style="float: left" id="form_search">
                        <div id="searchdivice" class="input-group" style="border:1px solid #cccccc; width:200px; border-radius:3px; height:34px; float:left;background-color:#fff;margin-right: 20px">
                            <div class="input-group-addon search" onclick="document.getElementById('form_search').submit()"></div>
                            <input id="user_search" name="search" type="text" placeholder="请输入用户昵称" class="form-control input-sm" style="height: 100%;border: none;padding-left: 0px;box-shadow:none;" value="<?php echo $this->search?>">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="table-responsive" style="padding: 10px 30px 0px 40px;font-size: 14px !important;">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>手机号</th>
                    <th>用户等级</th>
                    <th>借书次数</th>
                    <th>累计消费</th>
                    <th>信用</th>
                    <th>最后借书时间</th>
                    <th>状态</th>
                    <th style="text-align: center">操作</th>
                </tr>
                </thead>
                <tbody style="font-size: 13px !important;">

                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/jquery/js/jQuery-2.2.0.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/jquery/js/json2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/jquery/js/jquery.alerts.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/Common.js"></script>
<script type="text/javascript">

</script>
</body>
</html>
