<!DOCTYPE html>
<html>
<head lang="en">
    <title>小萝卜</title>
    <meta charset="UTF-8">
    <title></title>
    <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/scripts/jquery/css/jquery.alerts.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/scripts/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/styles/admin/style.css" />
    <style type="text/css">

    </style>
<body class="sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <div class="logo">
                <div class="logo-mini"></div>
                <div class="logo-lg"></div>
            </div>
            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="sidebar-toggle1" data-toggle="offcanvas" role="button"></a>
            </nav>
        </header>
        <div class="m_opacity"></div>
        <aside class="main-sidebar">
            <div id="stairhover" class="sidebar-menu">
                <ul>
                    <li data-href="/xlb/admin/index/index-list" class="active">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20" xml:space="preserve" width="16" height="16" style="width:16px;height:16px">
	                        <polygon points="10,0 0,11.1 3.5,11.1 3.5,20 7.5,20 7.5,15.5 12.5,15.5 12.5,20 16.5,20 16.5,11.1 20,11.1 "></polygon>
	                    </svg>
                        <span>首页</span>
                    </li>
                    <li data-href="/xlb/admin/index/user-list">
                        <svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
                            <g id="XMLID_5_">
                                <path id="XMLID_6_" class="st1" d="M8,10.3c-2.9,0-5.2-2.3-5.2-5.2C2.8,2.3,5.1,0,8,0c2.9,0,5.2,2.3,5.2,5.2
                                    C13.2,8,10.9,10.3,8,10.3L8,10.3L8,10.3z M8,1C5.7,1,3.8,2.9,3.8,5.2c0,2.3,1.9,4.1,4.2,4.1c2.3,0,4.2-1.8,4.2-4.1
                                    C12.2,2.9,10.3,1,8,1L8,1L8,1z M15.2,16h-0.4c-0.2,0-0.3-0.1-0.3-0.3c0-0.3-0.1-0.5-0.2-0.8c-0.4-1.5-1.4-2.8-2.7-3.6
                                    c-1.1,0.6-2.3,0.9-3.5,0.9c-1.2,0-2.4-0.3-3.5-0.9c-1.3,0.8-2.3,2.1-2.7,3.6c0,0-0.1,0.3-0.2,0.8c0,0.1-0.2,0.3-0.3,0.3H0.8
                                    c-0.2,0-0.3-0.1-0.3-0.3c0.3-2.4,1.8-4.5,3.9-5.6c1,0.7,2.2,1.1,3.5,1.1c1.3,0,2.5-0.4,3.5-1.1c2.1,1.1,3.6,3.2,3.9,5.6
                                    C15.4,15.9,15.3,16,15.2,16L15.2,16L15.2,16z"></path>
                            </g>
                        </svg>
                        <span>用户</span>
                    </li>
                    <li data-href="/xlb/admin/index/book-list">
                        <svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
                            <g id="XMLID_2_">
                                <path id="XMLID_7_" class="st1" d="M6,5.3H2.6C2.3,5.3,2,5.5,2,5.8c0,0.3,0.2,0.5,0.5,0.5H6c0.3,0,0.5-0.2,0.5-0.5
                                    C6.6,5.5,6.3,5.3,6,5.3L6,5.3z M6,8.5H2.6C2.3,8.5,2,8.7,2,9c0,0.3,0.2,0.5,0.5,0.5H6c0.3,0,0.5-0.2,0.5-0.5C6.6,8.7,6.3,8.5,6,8.5
                                    L6,8.5z M13.5,5.3h-3.5c-0.3,0-0.5,0.2-0.5,0.5c0,0.3,0.2,0.5,0.5,0.5h3.5c0.3,0,0.5-0.2,0.5-0.5C14.1,5.5,13.8,5.3,13.5,5.3
                                    L13.5,5.3z M13.5,8.5h-3.5C9.8,8.5,9.5,8.7,9.5,9c0,0.3,0.2,0.5,0.5,0.5h3.5c0.3,0,0.5-0.2,0.5-0.5C14.1,8.7,13.8,8.5,13.5,8.5
                                    L13.5,8.5z"></path>
                                <path id="XMLID_3_" class="st1" d="M14.4,0.7h-3.3C9.6,0.7,8.5,1.3,8,1.6C7.5,1.3,6.4,0.7,4.9,0.7H1.6C0.7,0.7,0,1.5,0,2.4v10.4
                                    c0,0.9,0.7,1.6,1.6,1.6h3.3c0,0,0,0,0.1,0C7.3,14.5,7.5,15,7.5,15c0.1,0.2,0.3,0.3,0.5,0.3c0,0,0,0,0,0c0,0,0,0,0,0
                                    c0.2,0,0.4-0.1,0.5-0.3c0,0,0.3-0.5,2.5-0.6c0,0,0,0,0.1,0h3.3c0.9,0,1.6-0.7,1.6-1.6V2.4C16,1.5,15.3,0.7,14.4,0.7L14.4,0.7z
                                     M6.9,13.6c-0.5-0.1-1.2-0.2-2.1-0.3c-0.4,0-0.8,0-1.2,0c-0.8,0-1.4,0-1.5,0H1.6c-0.3,0-0.6-0.3-0.6-0.6V2.4c0-0.3,0.3-0.6,0.6-0.6
                                    h3.3c0.7,0,1.4,0.2,2,0.4c0.2,0.1,0.4,0.2,0.5,0.3l0,8.2l0,3C7.3,13.7,7.1,13.6,6.9,13.6L6.9,13.6z M14.9,12.8
                                    c0,0.3-0.3,0.6-0.6,0.6h-0.5c-0.2,0-1.4-0.1-2.7,0c-0.8,0-1.5,0.1-2.1,0.3c-0.2,0-0.4,0.1-0.5,0.2l0-3l0-8.2
                                    c0.1-0.1,0.3-0.2,0.5-0.3c0.6-0.3,1.3-0.4,2-0.4h3.3c0.3,0,0.6,0.3,0.6,0.6L14.9,12.8L14.9,12.8L14.9,12.8z"></path>
                            </g>
                        </svg>
                        <span>绘本</span>
                    </li>
                    <li data-href="/xlb/admin/index/cabi-list" >
                        <svg version="1.1" id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
                            <g id="XMLID_9_">
                                <path id="XMLID_12_" class="st1" d="M10.5,1.3L10.5,1.3C10.5,1.4,10.5,1.3,10.5,1.3C10.5,1.3,10.5,1.3,10.5,1.3L10.5,1.3L10.5,1.3z
                                     M14.2,9.3H9.8c-0.3,0-0.5,0.2-0.6,0.4c-0.2,0.5-0.6,0.9-1.2,0.9c-0.5,0-1-0.4-1.2-0.9C6.9,9.5,6.6,9.3,6.4,9.3H2
                                    c-1,0-1.8,0.9-1.8,2V14c0,1.1,0.8,2,1.8,2h12.2c1,0,1.8-0.9,1.8-2v-2.7C16,10.2,15.2,9.3,14.2,9.3L14.2,9.3z M14.8,14
                                    c0,0.4-0.3,0.7-0.6,0.7H2c-0.3,0-0.6-0.3-0.6-0.7v-2.7c0-0.4,0.3-0.7,0.6-0.7h4C6.4,11.5,7.2,12,8.1,12c0.9,0,1.7-0.5,2.1-1.3h4
                                    c0.3,0,0.6,0.3,0.6,0.7L14.8,14L14.8,14z M11.8,4.7H6.9C6.6,4.7,6.3,4.4,6.3,4c0-0.4,0.3-0.7,0.6-0.7h4.9c0.3,0,0.6,0.3,0.6,0.7
                                    C12.4,4.4,12.1,4.7,11.8,4.7L11.8,4.7z M11.8,7.3H6.9C6.6,7.3,6.3,7,6.3,6.7C6.3,6.3,6.6,6,6.9,6h4.9c0.3,0,0.6,0.3,0.6,0.7
                                    C12.4,7,12.1,7.3,11.8,7.3L11.8,7.3z"></path>
                                <path id="XMLID_2_" class="st1" d="M3.8,2v7.5c0,0.4,0.3,0.7,0.6,0.7h1.2C6,10.2,5,9.9,5,9.5V2c0-0.4,0.3-0.7,0.6-0.7H13
                                    c0.3,0,0.6,0.3,0.6,0.7v7.5c0,0.4,0.3,0.7,0.6,0.7c0.3,0,0.6-0.3,0.6-0.7V2c0-1.1-0.8-2-1.8-2H5.7C4.6,0,3.8,0.9,3.8,2L3.8,2z"></path>
                                <path id="XMLID_1_" class="st1" d="M3.2,1.3c-1,0-1.8,0.9-1.8,2V10h1.2V3.3c0-0.4,0.3-0.7,0.6-0.7h1.1V1.3H3.2L3.2,1.3z"></path>
                            </g>
                        </svg>
                        <span>柜子</span>
                    </li>
                    <li data-href="/xlb/admin/index/active-list">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20" xml:space="preserve">
                            <g>
                                <path d="M17.3,1.3h1.3c0.7,0,1.3,0.6,1.3,1.3v4H0v-4c0-0.7,0.6-1.3,1.3-1.3h1.3v2c0,1.1,0.9,2,2,2s2-0.9,2-2v-2h6.7v2c0,1.1,0.9,2,2,2s2-0.9,2-2V1.3L17.3,1.3z"></path>
                                <path d="M0,8v10.7C0,19.4,0.6,20,1.3,20h17.4c0.7,0,1.3-0.6,1.3-1.3V8H0z M17.3,16c0,0.7-0.6,1.3-1.3,1.3h-4c-0.7,0-1.3-0.6-1.3-1.3v-2.7c0-0.7,0.6-1.3,1.3-1.3h4c0.7,0,1.3,0.6,1.3,1.3V16z"></path>
                                <polygon points="4,0 5.3,0 5.3,4 4,4"></polygon>
                                <polygon points="14.7,0 16,0 16,4 14.7,4"></polygon>
                            </g>
	                </svg>
                        <span>活动</span>
                    </li>
                    <li data-href="/xlb/admin/index/role-list">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 16 16" style="enable-background:new 0 0 16 16;" xml:space="preserve">
                            <g>
                                <path class="st0" d="M0.6,0C0.3,0,0,0.2,0,0.6v14.9C0,15.8,0.3,16,0.6,16c0.3,0,0.6-0.2,0.6-0.6V0.6C1.2,0.2,0.9,0,0.6,0z"></path>
                                <path class="st0" d="M6.3,11.4c0-0.1,0.1-0.4,0.1-0.4h-4c-0.2,0-0.3,0.2-0.3,0.3v2.3c0,0.2,0.2,0.3,0.3,0.3h4.7
                                    C6.5,13.2,6.2,12,6.3,11.4z"></path>
                                <path class="st0" d="M2.4,9.6h4.2c0.5-1.4,1.6-2.5,3-3H2.4c-0.2,0-0.3,0.2-0.3,0.3v2.3C2.1,9.4,2.2,9.6,2.4,9.6z"></path>
                                <path class="st0" d="M2.4,5.2h11c0.2,0,0.3-0.2,0.3-0.3V2.6c0-0.2-0.2-0.3-0.3-0.3h-11c-0.2,0-0.3,0.2-0.3,0.3v2.3
                                    C2.1,5,2.2,5.2,2.4,5.2z"></path>
                                <path class="st0" d="M16,12.1V11l-1.3-0.2c-0.1-0.3-0.2-0.6-0.4-0.9l0.8-1l-0.8-0.8l-1,0.8c-0.3-0.2-0.6-0.3-0.9-0.4l-0.2-1.3h-1.1
                                    l-0.2,1.3c-0.3,0.1-0.6,0.2-0.9,0.4L9,8.1L8.2,8.9l0.7,1c-0.2,0.3-0.3,0.6-0.4,0.9L7.2,11v1.1l1.3,0.2c0.1,0.3,0.2,0.6,0.4,0.9
                                    l-0.8,1.1L9,15l1.1-0.7c0.3,0.2,0.6,0.3,0.9,0.4l0.2,1.3h1.1l0.2-1.3c0.3-0.1,0.6-0.2,0.9-0.4l1.1,0.8l0.8-0.8l-0.8-1.1
                                    c0.2-0.3,0.3-0.6,0.4-0.9L16,12.1z M11.7,13.1c-0.8,0-1.5-0.7-1.5-1.5c0-0.8,0.7-1.5,1.5-1.5s1.5,0.7,1.5,1.5
                                    C13.2,12.4,12.5,13.1,11.7,13.1z"></path>
                            </g>
					    </svg>
                        <span>权限</span>
                    </li>
                </ul>
            </div>
        </aside>
        <div class="content-wrapper">
            <section class="content">
                <div class="fullscreenable">
                    <div id="min-height">
                        <div id="content">
                            <iframe src="" frameborder="0"></iframe>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/jquery/js/jQuery-2.2.0.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/jquery/js/json2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/Common.js"></script>
<script type="text/javascript">
    $(function () {
        //点击最小化菜单
        $('.sidebar-toggle1').click(function(){
            if ($('.sidebar-mini').hasClass('sidebar-collapse')) {
                $('.sidebar-mini').removeClass('sidebar-collapse');
            } else {
                $('.sidebar-mini').addClass('sidebar-collapse');
            }
        });

        //点击菜单跳转
        var $div = $('.main-sidebar > .sidebar-menu');
        $div.on('click', 'li[data-href]', function () {
            var href = $(this).data('href');
            if (!!href && href!='undefined') {
                var curSelf = $('#content iframe').attr('src');
                var curPos = curSelf.lastIndexOf('#');
                var curPar = curSelf.substr(curPos);
                var pos = href.lastIndexOf('#');
                var par = href.substr(pos);
                $('#content iframe').attr('src',href);
                sessionStorage.setItem('src', href);
                if(par != curPar && curPos !=-1 && pos != -1){
                    document.getElementById('iframe').contentWindow.location.reload(true);
                }
                //菜单增加样式
                if($(this).parents('li').data('href') == undefined){
                    $('#stairhover').find('ul li').removeClass('active');
                    $(this).addClass('active');
                }else{
                    $('#stairhover').find('ul li').removeClass('active');
                    $(this).parents('li').addClass('active');
                }
                $('.sidebar-mini').removeClass('sidebar-collapse');
            }

        });
    })
    window.onload = function () {
        var href = sessionStorage.getItem('src');
        if (null != href) {
            $('#content iframe').attr('src',href);
        } else {
            $('#content iframe').attr('src','/xlb/admin/index/index-list');
        }

    }
</script>
</body>
</html>