<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>小萝卜</title>
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/scripts/jquery/css/jquery.alerts.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/scripts/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/styles/admin/style.css" />
    <style type="text/css">
        .body {
            background-color: #7b7b7b;
            background-position: bottom left;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
        .wp {
            width: 360px;
            margin: 0 auto;
        }
        .form {
            position: relative;
            top: 200px;
            height: 300px;
            background-color: #fff;
            border-radius: 4px;
            font-size: 14px;
            color: #36393f;
        }
        #login{
            padding: 30px;
        }
        .register-button {
            min-width: 100px;
            height: 36px;
            font-size: 14px;
            color: #fff;
            background-color: #0d83c6;
            border: 1px solid #0d83c6;
            border-radius: 6px;
        }
    </style>
</head>
<body class="body">
    <div class="wp">
        <div class="form">
            <form id="login" method="post" action="/xlb/admin/index/login">
                <div class="padding_bottom_20">
                    <span>登录</span>
                    <span class="blod">小萝卜后台账号</span>
                </div>
                <div class="form-group">
                    <input id="username" name="username" class="form-control" placeholder="用户名" autofocus="" required="required" style="padding-right: 50px;" type="text" />
                </div>
                <div class="form-group" style="position: relative">
                    <input id="password" name="password" class="form-control" placeholder="密码" required="required" type="password"  style="padding-right: 50px;" />
                </div>
                <div class="form-group fwmf-marginbottom10">
                    <div id="errorMsg" style="color:red;font-size:12px;display:inline;"><?php echo $this->error;?></div>
                </div>
                <div style="text-align:center;margin-top: 42px;">
                    <button id="log" class="register-button" type="submit">登录</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>
