<!DOCTYPE html>
<html>
<head>
    <title>小萝卜</title>
    <meta charset="UTF-8">
    <title></title>
    <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/scripts/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/scripts/jquery/css/jquery.alerts.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/styles/admin/style.css" />
    <style type="text/css">
        li{
            display: inline-block;
            cursor: pointer;
        }
        a{
            color: #838a90;
        }
        a:hover {
            color: #4aacf3;
            text-decoration: none;
        }
        #add_user button{
            margin-right: 20px;
        }

        .display-none{
            display: none;
        }
        .form-control{
            width: 90%;
            float: left;
        }
        .xln_must_enter {
            color: #c00000;
            font-size: 16px;
            float: left;
            padding-left: 10px;
            height: 40px;
            line-height: 40px;
        }
        form .errMsg{
            color: #A94442;
        }
        .form-horizontal .form-group {
            margin: 0px 0px 20px 0px;
        }
        .control-input {
            min-height: 40px;
            float: left;
            color: #4d4d4d;
        }
        .form-horizontal .control-label {
            font-size: 12px;
            color: #121212;
            font-weight: normal;
            float: left;
            height: 40px;
            line-height: 40px;
            padding: 0px;
        }
        .input-group-addon.search {
            cursor: pointer;
            width: 34px;
            height: 34px;
            border: none;
            background: transparent url(/xlb/public/images/search.png) no-repeat scroll 10px 10px;
        }
        td>a{
            cursor: pointer;
        }
        .span_user{
            height: 40px;
            width: 50px;
            background: #2294e4;
            float: left;
            border: 1px solid #2294e4;
            border-radius: 0px 4px 4px 0px;
            padding: 0px;
            cursor: pointer;
        }
        #xz_sp button{
        }
        .right-left{
            position: absolute;
            right: 0px;
            top: 0px;
            overflow-y: auto;
            height: 100%;
            width: 0px;
            z-index: 9999;
            -webkit-transition: -webkit-transform .3s ease-in-out,width .3s ease-in-out;
            -moz-transition: -moz-transform .3s ease-in-out,width .3s ease-in-out;
            -o-transition: -o-transform .3s ease-in-out,width .3s ease-in-out;
            transition: transform .3s ease-in-out,width .3s ease-in-out;
            background-color: #fff;
            box-shadow: 0px 0px 13px #9f9f9f;
        }
        .book_display{
            width: 70%;
        }
        .book_info_flex{
            display: flex;
            flex-flow: row nowrap;
            justify-content: flex-start;
            width: 100%;
            height: 200px;
        }
        .book_info_img{
            width: 220px;
            height: 200px;
            margin: 0 10px;
            text-align: center;
        }
        .book_info_info{
            width: calc(100% - 220px);
            height: 200px;
            display: flex;
            flex-flow: column;
            margin-left: 50px;
        }
        .book_info_info_title{
            width: 200px;
            padding-left: 5px;
            margin: 4px 10px 0px 0px;
        }
        h1 {
            display: block;
            color: rgb(70, 184, 210);
            padding-bottom: 10px;
            font-family: 微软雅黑, 黑体, Verdana;
            font-size: 16px;
            font-weight: 500;
            margin: 0;
        }
        .book_info_info_title span{
            color: #333;
        }
        .book_info_info_title div {
            line-height: 190%;
        }
    </style>
</head>
<body style="height: 100%">
<div class="container" style="border-radius: 4px;height: 100%;width: 100%;background-color: #fff;overflow-y: auto">
    <div id="book_list">
        <div style="margin: 20px 20px 50px;">
            <div style="width:100%;color:#74767c;font-size:18px;">绘本列表</div>
            <div style="padding-right: 20px;">
                <div class="float-right">
                    <form action="/xlb/admin/book/index/page/1" style="float: left" id="form_search">
                        <div id="searchdivice" class="input-group" style="border:1px solid #cccccc; width:200px; border-radius:3px; height:34px; float:left;background-color:#fff;margin-right: 20px">
                            <div class="input-group-addon search" onclick="document.getElementById('form_search').submit()"></div>
                            <input id="book_search" name="search" type="text" placeholder="请输入绘本名称" class="form-control input-sm" style="height: 100%;border: none;padding-left: 0px;box-shadow:none;" value="<?php echo $this->search?>">
                        </div>
                    </form>
                    <button type="button" class="btn btn-primary" id="book_add">
                        <span class="glyphicon glyphicon-plus" style="font-size: 1px;padding-right: 5px;"></span>
                        添加绘本
                    </button>
                </div>
            </div>
        </div>
        <div class="table-responsive" style="padding: 10px 30px 0px 40px;font-size: 14px !important;">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>绘本ID</th>
                    <th>绘本名称</th>
                    <th>适读年龄</th>
                    <th>绘本作者</th>
                    <th>出版社</th>
                    <th>出版社日期</th>
                    <th>语种</th>
                    <th>评分</th>
                    <th style="text-align: center">操作</th>
                </tr>
                </thead>
                <tbody style="font-size: 13px !important;">
                <?php if (isset($this->rows['rows'])){?>
                    <?php foreach ($this->rows['rows'] as $table){?>
                        <?php echo "<tr data-id='{$table['id']}' data-desc='{$table['describe']}' data-picture='{$table['picture']}' data-theme='{$table['theme']}'>
                                <td>{$table['id']}</td>
                                <td><a class='book_name'>{$table['name']}</a></td>"?>
                        <?php echo "<td class='book_age_reading'>{$table['age_reading']}</td>"?>
                        <?php echo "<td class='book_author'>{$table['author']}</td>"?>
                        <?php echo "<td class='book_press'>{$table['press']}</td>"?>
                        <?php echo "<td class='book_press_data'>{$table['press_data']}</td>"?>
                        <?php echo "<td class='book_languages'>{$table['languages']}</td>"?>
                        <?php echo "<td class='book_score'>{$table['score']}</td>"?>
                        <?php echo "<td style='text-align: center'>
                            <ul>
                                <li><a class='book_edit'>编辑</a></li>
                                <li style='margin-left: 20px'><a class='book_share'>共享</a></li>
                                <li style='margin-left: 20px'><a class='book_del'>删除</a></li>
                            </ul></td></tr>"?>
                    <?php }?>
                <?php }?>
                </tbody>
            </table>
        </div>
        <?php if (isset($this->page)) {echo $this->page;}?>
    </div>
    <div class="book_info right-left" style="">
        <div style="margin: 20px 20px 50px;">
            <div id="book_info_title" style="width:100%;color:#74767c;font-size:18px;">绘本详情</div>
            <div style="padding-right: 20px;">
                <div class="float-right">
                    <button type="button" class="btn btn-primary user_back">
                        <span class="glyphicon glyphicon-arrow-left" style="font-size: 1px;padding-right: 5px;"></span>
                        返回
                    </button>
                </div>
            </div>
        </div>
        <div style="width: 70%;height: 100%;margin: 0 auto;">
            <div class="book_info_flex">
                <div class="book_info_img">
                    <img src="" alt="">
                </div>
                <div class="book_info_info">
                    <div class="book_info_info_title title" style="width: 100%">
                        <h1></h1>
                    </div>
                    <div class="book_info_info_title">
                        <div><span>语言：</span><span class="info_1"></span></div>
                        <div><span>标签：</span><span class="info_2">趣味类</span></div>
                        <div><span>适合年龄：</span><span class="info_3"></span></div>
                        <div><span>评分：</span><span class="info_4"></span></div>
                        <div><span>作者：</span><span class="info_5"></span></div>
                        <div><span>出版社：</span><span class="info_6"></span></div>
                        <div><span>出版日期：</span><span class="info_7"></span></div>
                    </div>
                </div>
            </div>
            <div style="margin-top: 10px;">
                <ul id="myTab" class="nav nav-tabs">
                    <li class="active">
                        <a href="#home" data-toggle="tab">内容简介</a>
                    </li>
                </ul>
                <div id="myTabContent" class="tab-content" style="border: 1px solid #ddd; border-top: 0px;">
                    <div class="tab-pane fade in active" id="home" style="padding: 10px 20px 10px">
                        <p style="text-indent: 30px;line-height: 190%;letter-spacing: 2px"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="share_book right-left">
        <div style="margin: 20px 20px 50px;">
            <div id="admin_add_title" style="width:100%;color:#74767c;font-size:18px;">共享绘本</div>
            <div style="padding-right: 20px;">
                <div class="float-right">
                    <button type="button" class="btn btn-primary user_back">
                        <span class="glyphicon glyphicon-arrow-left" style="font-size: 1px;padding-right: 5px;"></span>
                        返回
                    </button>
                </div>
            </div>
        </div>
        <div style="width:70%;height: 100%;margin: 0 auto;">
            <form class="form-horizontal" id="add_user" role="form">
                <div class="form-group display-none">
                    <input id="_id" class="form-control control-input" name="_id" type="text">
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2" for="_number" style="text-align:right;font-weight:normal;">
                        共享绘本编号：
                    </label>
                    <div class="col-sm-6">
                        <input id="_number" class="form-control control-input" name="_number" type="text" placeholder="请输入共享绘本编号" required>
                        <span class="xln_must_enter" >*</span>
                    </div>
                    <div class="errMsg col-sm-10 col-sm-offset-2 display-none"></div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="_share_price" style="text-align:right;font-weight:normal;">
                        共享价格：
                    </label>
                    <div class="col-sm-6">
                        <input id="_share_price" class="form-control control-input" name="_share_price" type="text" required placeholder="请输入共享价格">
                        <span class="xln_must_enter" >*</span>
                    </div>
                    <div class="errMsg col-sm-10 col-sm-offset-2  display-none"></div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="cabi_id" style="text-align:right;font-weight:normal;">
                        共享书柜：
                    </label>
                    <div class="col-sm-6">
                        <select  id="cabi_id" class="form-control control-input" name="cabi_id" >
                        </select>
                        <span class="xln_must_enter" >*</span>
                    </div>
                    <div class="errMsg col-sm-10 col-sm-offset-2  display-none"></div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="cs_id" style="text-align:right;font-weight:normal;">
                        共享格子：
                    </label>
                    <div class="col-sm-6">
                        <select  id="cs_id" class="form-control control-input" name="cs_id" >
                        </select>
                        <span class="xln_must_enter" >*</span>
                    </div>
                    <div class="errMsg col-sm-10 col-sm-offset-2  display-none"></div>
                </div>
                <!--<div class="form-group">
                    <label class="control-label col-sm-2" for="_space_num" style="text-align:right;font-weight:normal;">
                        共享绘本数：
                    </label>
                    <div class="col-sm-6">
                        <input id="_space_num" class="form-control control-input" name="_space_num" type="text" required placeholder="请输入共享绘本数">
                        <span class="xln_must_enter" >*</span>
                    </div>
                </div>-->
                <div class="form-group">
                    <label class="control-label col-sm-2" for="" style="text-align:right;font-weight:normal;"></label>
                    <div class="col-sm-6 control-input" style="margin-left:0px;">
                        <button type="button" class="btn btn-default user_back">取消</button>
                        <button type="button" class="btn btn-primary" id="save_book_continue">共享后继续</button>
                        <button type="button" class="btn btn-primary" id="save_book">共享</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/jquery/js/jQuery-2.2.0.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/jquery/js/json2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/jquery/js/jquery.alerts.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/Common.js"></script>
<script type="text/javascript">
    $(function () {

        //绘本详情
        $('.book_name').click(function () {
            $('.book_info').addClass('book_display');
            $('tr[class="active"]').removeClass('active');
            var tr = $(this).closest('tr');
            tr.addClass('active');
            $('.book_info_img>img').attr('src',tr.data('picture'));
            $('.title>h1').text(tr.find('td').eq(1).find('a').text());
            $('.info_1').text(tr.find('td').eq(6).text());
            $('.info_2').text(tr.data('theme'));
            $('.info_3').text(tr.find('td').eq(2).text());
            $('.info_4').text(tr.find('td').eq(7).text());
            $('.info_5').text(tr.find('td').eq(3).text());
            $('.info_6').text(tr.find('td').eq(4).text());
            $('.info_7').text(tr.find('td').eq(5).text());
            $('#home>p').text(tr.data('desc'));
        })

        //绘本列表
        $('.user_back').click(function () {
            $('.book_info').removeClass('book_display');
            $('.share_book').removeClass('book_display');
            $('tr[class="active"]').removeClass('active');
        });

        //共享绘本页
        $('.book_share').click(function () {
            var tr = $(this).closest('tr');
            myGet(url+'/xlb/admin/cabinet/getlist',function(json) {
                if (json.code == 0) {
                    jAlert(json.message);
                } else {
                    var cabis = json.data.cabis;
                    var casps = json.data.casps;
                    var str = '';
                    if (null != cabis && cabis.length > 0){
                        str = '';
                        var len = cabis.length;
                        for(var i = 0; i < len; ++i) {
                            str += '<option value="'+cabis[i]._id+'">'+cabis[i]._name+'</option>';
                        }
                        $('#cabi_id').html(str);
                    }
                    if (null != casps && casps.length > 0){
                        str = '';
                        var len = casps.length;
                        for(var i = 0; i < len; ++i) {
                            str += '<option value="'+casps[i].cs_id+'">'+casps[i].cs_no+'</option>';
                        }
                        $('#cs_id').html(str);
                    }
                }
            });
            $('.share_book').addClass('book_display');
            $('tr[class="active"]').removeClass('active');
            $('#_id').val(tr.data('id'))
        });

        //获取空格
        $('#cabi_id').change(function () {
            var id = $(this).val();
            myGet(url+'/xlb/admin/cabinet/getcasps/id/' + id,function(json) {
                if (json.code == 0) {
                    jAlert(json.message);
                } else {
                    var casps = json.data.casps;
                    var str = '';
                    if (null != casps && casps.length > 0){
                        str = '';
                        var len = casps.length;
                        for(var i = 0; i < len; ++i) {
                            str += '<option value="'+casps[i].cs_id+'">'+casps[i].cs_no+'</option>';
                        }
                        $('#cs_id').html(str);
                    }
                }
            });
        });

        //保存共享绘本
        $('#save_book').click(function () {
            myPost(url+'/xlb/admin/book/addshare',$("#add_user").serialize(),function (json) {
                if (json.code == 0) {
                    jAlert(json.message);
                } else {
                    jAlert(json.message);
                    window.location.reload();
                }
            });
        });

        //保存共享绘本后继续
        $('#save_book_continue').click(function () {
            myPost(url+'/xlb/admin/book/addshare',$("#add_user").serialize(),function (json) {
                if (json.code == 0) {
                    jAlert(json.message);
                } else {
                    jAlert(json.message);
                    $('#_number').val('');
                    $('#_share_price').val('');
                    $('#cabi_id').trigger('change');
                }
            });
        });
    })
</script>
</body>
</html>
