<!DOCTYPE html>
<html>
<head>
    <title>小萝卜</title>
    <meta charset="UTF-8">
    <title></title>
    <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/scripts/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/scripts/jquery/css/jquery.alerts.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/styles/admin/style.css" />
    <style type="text/css">
        li{
            display: inline-block;
            cursor: pointer;
        }
        a{
            color: #838a90;
        }
        a:hover {
            color: #4aacf3;
            text-decoration: none;
        }
        #add_user button{
            margin-right: 20px;
        }

        .display-none{
            display: none;
        }
        .form-control{
            width: 90%;
            float: left;
        }
        .xln_must_enter {
            color: #c00000;
            font-size: 16px;
            float: left;
            padding-left: 10px;
            height: 40px;
            line-height: 40px;
        }
        form .errMsg{
            color: #A94442;
        }
        .form-horizontal .form-group {
            margin: 0px 0px 20px 0px;
        }
        .control-input {
            min-height: 40px;
            float: left;
            color: #4d4d4d;
        }
        .form-horizontal .control-label {
            font-size: 12px;
            color: #121212;
            font-weight: normal;
            float: left;
            height: 40px;
            line-height: 40px;
            padding: 0px;
        }
        .input-group-addon.search {
            cursor: pointer;
            width: 34px;
            height: 34px;
            border: none;
            background: transparent url(/xlb/public/images/search.png) no-repeat scroll 10px 10px;
        }
        td>a{
            cursor: pointer;
        }
        .span_user{
            height: 40px;
            width: 50px;
            background: #2294e4;
            float: left;
            border: 1px solid #2294e4;
            border-radius: 0px 4px 4px 0px;
            padding: 0px;
            cursor: pointer;
        }
        #xz_sp button{
        }
    </style>
</head>
<body style="height: 100%">
<div class="container" style="border-radius: 4px;height: 100%;width: 100%;background-color: #fff;min-height: 700px;overflow-y: auto">
    <div id="cabinet_list">
        <div style="margin: 20px 20px 50px;">
            <div style="width:100%;color:#74767c;font-size:18px;">绘本列表</div>
            <div style="padding-right: 20px;">
                <div class="float-right">
                    <form action="/xlb/admin/book/index/page/1" style="float: left" id="form_search">
                        <div id="searchdivice" class="input-group" style="border:1px solid #cccccc; width:200px; border-radius:3px; height:34px; float:left;background-color:#fff;margin-right: 20px">
                            <div class="input-group-addon search" onclick="document.getElementById('form_search').submit()"></div>
                            <input id="cabi_search" name="search" type="text" placeholder="请输入绘本名称" class="form-control input-sm" style="height: 100%;border: none;padding-left: 0px;box-shadow:none;" value="<?php echo $this->search?>">
                        </div>
                    </form>
                    <button type="button" class="btn btn-primary" id="cabi_add">
                        <span class="glyphicon glyphicon-plus" style="font-size: 1px;padding-right: 5px;"></span>
                        添加绘本
                    </button>
                </div>
            </div>
        </div>
        <div class="table-responsive" style="padding: 10px 30px 0px 40px;font-size: 14px !important;">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>绘本ID</th>
                    <th>绘本名称</th>
                    <th>适读年龄</th>
                    <th>绘本作者</th>
                    <th>出版社</th>
                    <th>出版社日期</th>
                    <th>语种</th>
                    <th>评分</th>
                    <th style="text-align: center">操作</th>
                </tr>
                </thead>
                <tbody style="font-size: 13px !important;">
                <?php if (isset($this->rows['rows'])){?>
                    <?php foreach ($this->rows['rows'] as $table){?>
                        <?php echo "<tr data-id='{$table['id']}' data-desc='{$table['describe']}'><td>{$table['id']}</td><td><a>{$table['name']}</a></td>"?>
                        <?php echo "<td >{$table['age_reading']}</td>"?>
                        <?php echo "<td>{$table['author']}</td>"?>
                        <?php echo "<td>{$table['press']}</td>"?>
                        <?php echo "<td>{$table['press_data']}</td>"?>
                        <?php echo "<td>{$table['languages']}</td>"?>
                        <?php echo "<td>{$table['score']}</td>"?>
                        <?php echo "<td style='text-align: center'>
                            <ul>
                                <li><a class='book_edit'>编辑</a></li>
                                <li style='margin-left: 20px'><a class='cabi_enable'>共享</a></li>
                                <li style='margin-left: 20px'><a class='cabi_del'>删除</a></li>
                            </ul></td></tr>"?>
                    <?php }?>
                <?php }?>
                </tbody>
            </table>
        </div>
        <?php if (isset($this->page)) {echo $this->page;}?>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/jquery/js/jQuery-2.2.0.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/jquery/js/json2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/jquery/js/jquery.alerts.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/scripts/Common.js"></script>
<script type="text/javascript">
</script>
</body>
</html>
